"""
Test script for Complete Stress Detection System
Tests all 4 models + recommendations pipeline
"""

import requests
import json
import time
from datetime import datetime

# Configuration
BACKEND_URL = "http://localhost:8000"
TEST_USER = "test_student_001"

# Colors for output
GREEN = '\033[92m'
RED = '\033[91m'
YELLOW = '\033[93m'
BLUE = '\033[94m'
END = '\033[0m'

def print_header(title):
    """Print formatted header"""
    print(f"\n{BLUE}{'='*70}")
    print(f"{title}")
    print(f"{'='*70}{END}\n")

def print_success(msg):
    """Print success message"""
    print(f"{GREEN}✅ {msg}{END}")

def print_error(msg):
    """Print error message"""
    print(f"{RED}❌ {msg}{END}")

def print_info(msg):
    """Print info message"""
    print(f"{YELLOW}ℹ️  {msg}{END}")

def test_health():
    """Test 1: Check backend health"""
    print_header("TEST 1: Backend Health Check")
    
    try:
        response = requests.get(f"{BACKEND_URL}/health")
        if response.status_code == 200:
            data = response.json()
            print_success(f"Backend is running on port {data.get('port', 8000)}")
            print(f"   Status: {data.get('status')}")
            print(f"   Timestamp: {data.get('timestamp')}")
            
            endpoints = data.get('available_endpoints', [])
            print(f"   Available endpoints: {len(endpoints)}")
            for ep in endpoints:
                print(f"     • {ep}")
            
            return True
        else:
            print_error(f"Unexpected status code: {response.status_code}")
            return False
    except Exception as e:
        print_error(f"Cannot reach backend: {e}")
        print_info(f"Make sure backend is running: python main.py")
        return False

def test_recommendations():
    """Test 2: Get AI recommendations from 3 scores"""
    print_header("TEST 2: Get Recommendations (3 Scores → Gemini)")
    
    test_cases = [
        {
            "name": "Low Stress Profile",
            "data": {
                "user_id": TEST_USER,
                "audio_score": 20,
                "digital_score": 25,
                "physical_score": 30
            },
            "expected_level": "low"
        },
        {
            "name": "Moderate Stress Profile",
            "data": {
                "user_id": TEST_USER,
                "audio_score": 45,
                "digital_score": 60,
                "physical_score": 35
            },
            "expected_level": "moderate"
        },
        {
            "name": "High Stress Profile",
            "data": {
                "user_id": TEST_USER,
                "audio_score": 80,
                "digital_score": 85,
                "physical_score": 75
            },
            "expected_level": "high"
        }
    ]
    
    all_passed = True
    
    for i, test_case in enumerate(test_cases, 1):
        print(f"\n  Test Case {i}: {test_case['name']}")
        print(f"  Sending: {test_case['data']}")
        
        try:
            # Send request
            start_time = time.time()
            response = requests.post(
                f"{BACKEND_URL}/get-recommendations",
                json=test_case['data'],
                timeout=10
            )
            elapsed = time.time() - start_time
            
            if response.status_code == 200:
                data = response.json()
                
                # Extract info
                scores = data.get('scores', {})
                stress = data.get('stress_analysis', {})
                recs = data.get('recommendations', [])
                
                print(f"  Response time: {elapsed:.2f}s")
                print_success(f"Got response for {test_case['name']}")
                
                # Print scores
                print(f"\n    Scores:")
                print(f"      Audio:    {scores.get('audio', 0)}/100")
                print(f"      Digital:  {scores.get('digital', 0)}/100")
                print(f"      Physical: {scores.get('physical', 0)}/100")
                print(f"      Average:  {scores.get('average', 0):.1f}/100")
                
                # Print stress analysis
                print(f"\n    Stress Analysis:")
                print(f"      Level: {stress.get('level', 'unknown')}")
                print(f"      Category: {stress.get('category', 'N/A')}")
                print(f"      Primary Stressor: {stress.get('primary_stressor', 'N/A')}")
                
                # Print recommendations
                print(f"\n    Recommendations (Generated by Gemini):")
                for j, rec in enumerate(recs, 1):
                    print(f"\n      {j}. {rec.get('title', 'N/A')}")
                    print(f"         Priority: {rec.get('priority', 'N/A')}")
                    print(f"         Duration: {rec.get('duration', 'N/A')}")
                    print(f"         Action: {rec.get('action', 'N/A')[:60]}...")
                    print(f"         Motivation: {rec.get('motivation', 'N/A')}")
                
                print(f"\n    Generated by: {data.get('generated_by', 'N/A')}")
                print(f"    Model: {data.get('model', 'N/A')}")
                
            else:
                print_error(f"Request failed with status {response.status_code}")
                print(f"Response: {response.text}")
                all_passed = False
                
        except requests.exceptions.Timeout:
            print_error(f"Request timed out (>10s)")
            print_info("Gemini calls can take 2-3 seconds. This is normal.")
            all_passed = False
        except Exception as e:
            print_error(f"Error: {e}")
            all_passed = False
        
        # Wait between requests
        if i < len(test_cases):
            print(f"\n  Waiting 2 seconds before next test...")
            time.sleep(2)
    
    return all_passed

def test_model_info():
    """Test 3: verify Random Forest model is loaded"""
    print_header("TEST 3: Random Forest Model Status")
    
    try:
        # Test physical activity (which uses the model)
        test_data = {
            "acc_x": 0.5,
            "acc_y": 9.8,
            "acc_z": 0.2,
            "gyro_x": 0.1,
            "gyro_y": 0.2,
            "gyro_z": 0.1,
            "activity_history": ["STANDING", "WALKING"],
            "sitting_duration_minutes": 15
        }
        
        response = requests.post(
            f"{BACKEND_URL}/physical_activity",
            json=test_data
        )
        
        if response.status_code == 200:
            data = response.json()
            details = data.get('details', {})
            
            print_success("Random Forest model is loaded and responding")
            print(f"\n  Model Details:")
            print(f"    Type: {details.get('model', 'N/A')}")
            print(f"    Accuracy: {details.get('accuracy', 'N/A')}")
            print(f"    Features: {details.get('features_used', 'N/A')}")
            print(f"    Status: {details.get('model_status', 'N/A')}")
            
            # Print prediction
            print(f"\n  Prediction:")
            print(f"    Detected Activity: {data.get('activity', 'N/A')}")
            print(f"    Stress Score: {data.get('physical_stress_score', 0):.0f}°")
            print(f"    Movement Intensity: {data.get('movement_intensity', 0):.0f}%")
            
            return True
        else:
            print_error(f"Model test failed: {response.status_code}")
            return False
            
    except Exception as e:
        print_error(f"Error testing model: {e}")
        return False

def run_all_tests():
    """Run all tests"""
    print_header("🧪 COMPLETE SYSTEM TEST SUITE")
    print(f"Backend URL: {BACKEND_URL}")
    print(f"Test User: {TEST_USER}")
    print(f"Timestamp: {datetime.now().isoformat()}")
    
    results = []
    
    # Test 1: Health
    print("\n[1/3] Testing backend connection...")
    results.append(("Backend Health", test_health()))
    
    if not results[0][1]:
        print_error("Backend is not running. Skipping remaining tests.")
        print_info("Start backend with: conda activate stress_model && python main.py")
        return
    
    # Test 2: Recommendations
    print("\n[2/3] Testing AI recommendations (LanGraph + Gemini)...")
    results.append(("Recommendations", test_recommendations()))
    
    # Test 3: Model
    print("\n[3/3] Testing Random Forest model...")
    results.append(("Random Forest Model", test_model_info()))
    
    # Summary
    print_header("📊 TEST SUMMARY")
    
    all_passed = True
    for test_name, passed in results:
        status = f"{GREEN}PASSED{END}" if passed else f"{RED}FAILED{END}"
        print(f"  {test_name}: {status}")
        if not passed:
            all_passed = False
    
    print()
    if all_passed:
        print_success("All tests passed! System is ready.")
        print("\nNext steps:")
        print(f"  1. Get Google Gemini API key: https://ai.google.dev/")
        print(f"  2. Create .env file with: GOOGLE_API_KEY=your-key")
        print(f"  3. Restart backend: python main.py")
        print(f"  4. Start mobile app: flutter run")
    else:
        print_error("Some tests failed. Check errors above.")
        print("\nTroubleshooting:")
        print(f"  • Backend running? python main.py")
        print(f"  • API key set? Create .env file")
        print(f"  • Internet connection? Required for Gemini")
        print(f"  • Packages installed? pip install -r requirements.txt")

if __name__ == "__main__":
    try:
        run_all_tests()
    except KeyboardInterrupt:
        print(f"\n{YELLOW}Tests interrupted by user{END}")
    except Exception as e:
        print(f"\n{RED}Unexpected error: {e}{END}")
