// File generated by the FlutterFire CLI.
// For more information, please visit https://firebase.flutter.dev
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFMq81XKEbZMcrpDcdjC_VD40ydWMPGmE',
    appId: '1:969548033:web:c70a938aa9a1cd34587b00',
    messagingSenderId: '969548033',
    projectId: 'student-stress-app',
    authDomain: 'student-stress-app.firebaseapp.com',
    storageBucket: 'student-stress-app.firebasestorage.app',
    measurementId: 'G-CBZG5K27TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrrfNGvYh7bu7UGD_Aivm9EY-sF7Whhzc',
    appId: '1:969548033:android:4cbbb153cc96ba48587b00',
    messagingSenderId: '969548033',
    projectId: 'student-stress-app',
    storageBucket: 'student-stress-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqY2HK_YPEfRw-rMwkxloTPdfeICXpG2c',
    appId: '1:969548033:ios:c442f91dc0f12e6a587b00',
    messagingSenderId: '969548033',
    projectId: 'student-stress-app',
    storageBucket: 'student-stress-app.firebasestorage.app',
    iosBundleId: 'com.example.studentStressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqY2HK_YPEfRw-rMwkxloTPdfeICXpG2c',
    appId: '1:969548033:ios:c442f91dc0f12e6a587b00',
    messagingSenderId: '969548033',
    projectId: 'student-stress-app',
    storageBucket: 'student-stress-app.firebasestorage.app',
    iosBundleId: 'com.example.studentStressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFMq81XKEbZMcrpDcdjC_VD40ydWMPGmE',
    appId: '1:969548033:web:4af002c40faca586587b00',
    messagingSenderId: '969548033',
    projectId: 'student-stress-app',
    authDomain: 'student-stress-app.firebaseapp.com',
    storageBucket: 'student-stress-app.firebasestorage.app',
    measurementId: 'G-8478RYSZ0J',
  );

}